// Code generated by "stringer -type=OrderState --trimprefix=OrderState"; DO NOT EDIT.

package bridge

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OrderStateSubmitted-0]
	_ = x[OrderStateRunning-1]
	_ = x[OrderStateCompleted-2]
	_ = x[OrderStatePaid-3]
	_ = x[OrderStateRefunded-4]
	_ = x[OrderStateJobError-5]
	_ = x[OrderStateFailed-6]
}

const _OrderState_name = "SubmittedRunningCompletedPaidRefundedJobErrorFailed"

var _OrderState_index = [...]uint8{0, 9, 16, 25, 29, 37, 45, 51}

func (i OrderState) String() string {
	if i < 0 || i >= OrderState(len(_OrderState_index)-1) {
		return "OrderState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OrderState_name[_OrderState_index[i]:_OrderState_index[i+1]]
}
